steps:
  # --- PASO 1: Obtener TODOS los secretos (Corregido con COMILLAS y -n) ---
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Usamos echo -n "$(...)" para capturar el valor exacto SIN newline
        echo -n "$(gcloud secrets versions access latest --secret="RECAPTCHA_SITE_KEY")" > /workspace/recaptcha-key.txt
        echo -n "$(gcloud secrets versions access latest --secret="BACKEND_URL")" > /workspace/backend-url.txt
        echo -n "$(gcloud secrets versions access latest --secret="CHATBOT_ENABLED")" > /workspace/chatbot-enabled.txt
        
        # Depuración segura (para verificar el build)
        echo "============================================="
        echo "DEPURACIÓN DE SECRETOS (VERIFICANDO LONGITUDES)"
        echo "  RECAPTCHA_SITE_KEY: $(cat /workspace/recaptcha-key.txt | wc -c) caracteres"
        echo "  BACKEND_URL: $(cat /workspace/backend-url.txt | wc -c) caracteres"
        echo "  CHATBOT_ENABLED: $(cat /workspace/chatbot-enabled.txt | wc -c) caracteres"
        echo "============================================="
    id: Get Secrets

  # --- PASO 2: Construir la imagen (FORZANDO SIN CACHÉ) ---
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --no-cache \
          --build-arg NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$(cat /workspace/recaptcha-key.txt) \
          --build-arg NEXT_PUBLIC_BACKEND_URL=$(cat /workspace/backend-url.txt) \
          --build-arg NEXT_PUBLIC_CHATBOT_ENABLED=$(cat /workspace/chatbot-enabled.txt) \
          --tag="gcr.io/almapidev/my-resume-react:latest" .
    id: Build
    waitFor:
      - Get Secrets

  # --- PASOS 3 y 4 (Push y Deploy) no cambian ---
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/almapidev/my-resume-react:latest']
    id: Push
    waitFor:
      - Build

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-resume-react'
      - '--image'
      - 'gcr.io/almapidev/my-resume-react:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      # ... (resto de tus args de deploy)
    id: Deploy
    waitFor:
      - Push

images:
  - 'gcr.io/almapidev/my-resume-react:latest'

# --- AÑADE ESTE BLOQUE AL FINAL ---
options:
  logging: CLOUD_LOGGING_ONLY