# cloudbuild.yaml

steps:
  # 1. Obtiene el secreto de Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud secrets versions access latest --secret="RECAPTCHA_SITE_KEY" > /workspace/recaptcha-key.txt'

  # 2. Construye la imagen, pasando el secreto como un argumento de build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker build --tag="gcr.io/almapidev/my-resume-react:latest" .'

  # 3. Sube la imagen a Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/almapidev/my-resume-react:latest']

  # 4. Despliega la imagen final en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-resume-react'
      - '--image'
      - 'gcr.io/almapidev/my-resume-react:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - '251107984645-compute@developer.gserviceaccount.com'
      - '--set-env-vars'
      - 'RECAPTCHA_SITE_KEY=$(cat /workspace/recaptcha-key.txt)'

images:
  - 'gcr.io/almapidev/my-resume-react:latest'